apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: wilcard-example-com-tls
  namespace: letsencrypt-gcloud-balancer
spec:
  secretName: wilcard-example-com-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
    - "*.example.com"
  acme:
    config:
      - dns01:
          provider: cf-dns
        domains:
          - "*.example.com"
